import 'bootstrap/dist/css/bootstrap.min.css';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ background: "rgb(138 170 242)", textAlign: "center", padding: "40px 0" }}>
          <h2>Header</h2>
        </header>
        {children}
        <footer style={{ background: "rgb(138 170 242)", textAlign: "center", padding: "40px 0" }}>
          <h2>Footer</h2>
        </footer>
      </body>
    </html>
  )
}
